version: '3.1'
services:
  app:
    container_name: stock-spring-app
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - product-stock-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-stock-db:5432/product-stock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  product-stock-db:
    image: postgres
    container_name: stock-psql-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-stock
