version: '3.1'
services:
  app:
    container_name: image-spring-app
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - product-image-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-image-db:5432/product-image
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  product-image-db:
    image: postgres
    container_name: image-psql-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-image
